lavd/avfoundation: Use correct preprocessing directive
Fixes compilation, introduced in 5207a56.

src/libavdevice/avfoundation.m:799:10: error: invalid preprocessing directive
        #elseif (TARGET_OS_OSX && __MAC_OS_X_VERSION_MAX_ALLOWED < 140000)